name: mahjong_score_note
description: 麻雀の記録をつけるアプリ
version: 1.0.0+20231025
environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  path: ^1.8.0
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true